import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import AppWalletProvider from "@/components/component/AppWalletProvider";
import Script from "next/script";
import Head from "next/head";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RedBit",
  description: "Generated by create next app",
};

// const GoogleApiKey = process.env.NEXT_PUBLIC_GOOGLE_API;

const LoginLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <title>RedBit</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
        <AppWalletProvider>
          {children}
          <Toaster />
        </AppWalletProvider>
        {/* <Script
          src={`https://maps.googleapis.com/maps/api/js?key=${GoogleApiKey}&libraries=places`}
          strategy="lazyOnload"
        /> */}
      </body>
    </html>
  );
};

export default LoginLayout;
